name: Build Docker
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["linux/amd64", "linux/arm64", "linux/arm/v7"]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v1
      - name: Build and publish
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: matrix.platform
          tags: lol3r/tunneler:latest
